Write a program that loads (read) an XML document and prints out the itemid
and the number of words in < text > of the document

In [17]:
xml_file = open("./h.xml")
s = xml_file.read()


In [3]:
import xml.etree.ElementTree as ET
mytree = ET.parse('h.xml')
myroot = mytree.getroot()

<Element 'newsitem' at 0x7f99911e2ae0>

In [5]:
myroot.get("itemid")

'741299'

In [18]:
num_words = 0
for e in myroot.find("text"):
    print(e.text)
    num_words += len(e.text.split(" "))
num_words

J.J. Lehto of Finland and Steve Soper of Britain drove their ailing McLaren to victory in the fifth round of the world GT championship on Sunday, beating the Mercedes of German Bernd Schneider and Austrian Alexander Wurz by 15 seconds.
Their victory enabled them to open up a 16-point lead in the overall standings over Schneider, who mounted a strong challenge on the struggling leaders in the final minutes of the four-hour race.
But Soper, struggling with the car's handling caused by a broken undertray, just managed to hold on for the win.
Lehto had opened up a lead of over 90 seconds during a mid-race downpour in the Ardennes mountains.
"I thought that everyone else was driving on dry-weather tyres," he joked afterwards.
"We swapped to rain tyres at exactly the right time and I was able to push hard and open up a big lead."
Third to finish was the Porsche of France's Bob Wollek and Yannick Dalmas and Belgian Thierry Boutsen.
The Belgian, a former Formula One driver, switched from the c

190

A consensus string x is a string of length n formed from a collection by taking the most 
common symbol at each position; the j
th symbol of x therefore corresponds to the symbol 
having the maximum value in the j
th column of the profile matrix. Of course, there may 
be more than one most common symbol, leading to multiple possible consensus strings

In [116]:
import numpy as np
DNA = list("ACGT")

def pre_process(file_path):
    seq_1 = open(file_path).read()
    seq_1.split("\n")
    def f(row:str)->bool:
        return not row.startswith(">")
    dna_strings = list(filter(f, seq_1.split("\n")))
    data = []
    num_columns = len(dna_strings[0])
    for row in dna_strings:
        new_list = list(row)
        data.append(new_list+['[EMPTY]'] * (num_columns - len(new_list)))

    array = np.array([np.array(l) for l in  data], dtype=object)
    
    return array

In [117]:
seq_1 = pre_process("seq1.txt")
seq_1.shape



(7, 9)

In [118]:
def get_profile_matrix(data):
    P = np.ones( (len(DNA), data.shape[1]), dtype=np.int32)
    for i, alphbetics in enumerate(DNA):
        P[i:]=np.sum( data == alphbetics, axis=0)

    return P

P = get_profile_matrix(seq_1)
P

array([[5, 1, 0, 0, 5, 5, 0, 0, 0],
       [0, 0, 1, 4, 2, 0, 6, 1, 0],
       [1, 1, 6, 3, 0, 1, 0, 0, 4],
       [1, 5, 0, 0, 0, 1, 1, 6, 3]], dtype=int32)

In [119]:
def get_consensus_string(P:np.ndarray):
    s = ""
    max_indics = np.argmax(P,axis=0)
    print(max_indics)
    for i in max_indics:
        s += DNA[i]
    return s

get_consensus_string(P)

[0 3 2 1 0 0 1 3 2]


'ATGCAACTG'

In [121]:
def compute_consensus_string(file_path):
    seq = pre_process(file_path)
    print(seq.shape)
    P = get_profile_matrix(seq)
    s = get_consensus_string(P)
    return s

compute_consensus_string("seq1.txt")
    

(7, 9)
[0 3 2 1 0 0 1 3 2]


'ATGCAACTG'

In [122]:
compute_consensus_string("seq3.txt")


(160, 60)
[3 1 3 0 3 1 0 2 2 3 3 1 3 2 2 3 0 0 3 2 0 2 2 3 0 2 2 0 1 0 2 3 2 3 1 3 2
 2 2 1 3 3 2 3 3 3 0 1 2 0 3 1 0 1 3 2 1 0 2 2]


'TCTATCAGGTTCTGGTAATGAGGTAGGACAGTGTCTGGGCTTGTTTACGATCACTGCAGG'